package ssg.front.ssgsearchtestwebapp

import org.junit.Test
import org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document
import org.springframework.restdocs.payload.PayloadDocumentation.*
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post
import org.springframework.test.web.servlet.result.MockMvcResultHandlers

class SearchControllerTest : MockMvcBase() {

    @Test
    @Throws(Exception::class)
    fun 검색() {
        mockMvc.perform(
                post("/search/es_disp")
                        .contentType("application/json;charset=utf-8")
                        .content("""
{
    "userInfo": {
        "et": 1549607450211,
        "currentUrl": null,
        "zone": null,
        "requestId": null,
        "login": false,
        "userId": "",
        "userNm": null,
        "loginYn": "N",
        "orgNo": null,
        "occuCd": null,
        "sysDivCd": null,
        "occuUserDivCd": null,
        "posiCd": null,
        "dptsMdYn": null,
        "blngSiteNo": null,
        "webSecurityYN": "N",
        "remoteAddress": "127.0.0.1",
        "requestMap": {
            "queryString": "brandId=3000016643",
            "requestURL": "http://local-shinsegaemall.ssg.com:8073/special/global/brandShop.ssg",
            "headerUserAgent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Whale/1.4.63.11 Safari/537.36",
            "headerReferer": "http://local-shinsegaemall.ssg.com/special/global/sub.ssg?ctgId=6000015289",
            "cookiePcId": "15495979722182479970365",
            "cookieMemberID": null
        },
        "loginRemoteAddress": null,
        "serverName": "local-shinsegaemall.ssg.com",
        "ver": "0",
        "controllerCacheKey": null,
        "fsId": "pml9g43j000001lq0yw0",
        "fsIdDay": "pmlguolq0yw3j0000017",
        "mbrId": "",
        "mbrType": "B2C",
        "mbrCoId": "000000",
        "adultYn": "N",
        "loginTime": null,
        "emplYn": "N",
        "mbrTypeCd": null,
        "familyYn": null,
        "aloginToken": "",
        "locale": {
            "locale": "ko_KR",
            "languageTag": "ko-KR",
            "language": "ko",
            "googleTranslation": "/ko/ko",
            "ssgCurrency": {
                "currency": "KRW",
                "commCdNo": "120"
            }
        },
        "currency": {
            "currency": "KRW",
            "commCdNo": "120"
        },
        "keepLogin": "N",
        "mobileLoginRefresh": "0",
        "mbrNm": null,
        "mbrLoginId": null,
        "mbrcoLogoImgPathNm": null,
        "mbrSvcSiteLst": "0000^0000^0000",
        "deviceCd": "10",
        "deviceDivCd": "10",
        "deviceDtlCd": "10",
        "ckWhere": "direct_shinsegae",
        "pushWhere": null,
        "mckWhere": "",
        "sid": null,
        "plzcmtLitmitYn": null,
        "perdcShppYn": "N",
        "mbrcoNm": null,
        "mbrGrdCd": null,
        "mvnoYn": "N",
        "sguid": null,
        "vvipYn": "N",
        "birthday": "",
        "dptVipYn": "N",
        "dmId": null,
        "updateAffP": false,
        "affP1": null,
        "affP2": null,
        "affP3": null,
        "affP4": null,
        "affP5": null,
        "mbrGrdId": null,
        "shppLocSeq": "0",
        "shipZipCd": "04781",
        "emSaleStrNo": "2034",
        "trSaleStrNo": "2154",
        "bnSaleStrNo": "2451",
        "sdSaleStrNo": "0000",
        "sdSaleStrNm": "점포명",
        "bnSaleStrNm": "점포명",
        "trSaleStrNm": "점포명",
        "emSaleStrNm": "점포명",
        "emRsvtShppPsblYn": "Y",
        "trRsvtShppPsblYn": "N",
        "emHolyShppSalestrNo": "2034",
        "trHolyShppSalestrNo": "2154",
        "emSaleStrCenterYn": "N",
        "bnSaleStrCenterYn": "N",
        "sdRsvtShppPsblYn": "N",
        "emDualSaleStrNo": "0000",
        "cartMbrId": "",
        "hwSaleStrNo": "2468",
        "hwRsvtShppPsblYn": "N",
        "hwHolyShppSalestrNo": "",
        "hwSaleStrCenterYn": "N",
        "hwSaleStrNm": "점포명",
        "loginLimitYn": null,
        "ordLimitYn": null,
        "email": null,
        "phoneNumber": null,
        "adminYn": "N",
        "chnlId": "0000015203",
        "updatedCkWhere": true,
        "cacheMode": true,
        "cx": "N",
        "responseBodyContentType": null,
        "tempPT": null,
        "countryCode": "N/A",
        "firstCkwhere": false,
        "firstPcid": false,
        "firstFsid": false,
        "redirectResponse": false,
        "firstAppStart": false,
        "ga": "00",
        "thehowdy": false,
        "howdy": false,
        "domainSiteNo": null,
        "depth1": null,
        "searchFail": null,
        "itemSiteNo": null,
        "itemSalestrNo": null,
        "mobileAppNo": null,
        "bkWhere": "",
        "pushId": "",
        "firstPushId": false,
        "firstPushInfo": false,
        "pushDtlId": "",
        "ajaxRequest": false,
        "orderTracking": null,
        "currentTimeMillis": "1549607823871",
        "viewCacheProcess": "NoViewCache",
        "prevMbrId": "",
        "talk": "N",
        "bnRsvtShppPsblYn": "N",
        "bnHolyShppSalestrNo": "",
        "pcId": "15495979722182479970365",
        "requestFfirstCookie": null,
        "changedCkwhereOrPushId": false,
        "language": "ko",
        "foreignRemoteAddress": false,
        "b2EYN": false,
        "mbrType2": "B2C",
        "cacheId": "front-",
        "controllerCacheKeyExpire": null,
        "maskingEmail": "",
        "maskingPhoneNumber": "",
        "genderByPT": "NONE",
        "ageForTracking": "",
        "changedFfirst": false,
        "ffirstCookie": "0000",
        "forTrackingItemView": {
            "dispCtgId": null,
            "stdCtgId": null,
            "brandId": null,
            "sellPrice": null,
            "bestAmt": null
        },
        "mobileWebOs": "",
        "notDefaultLocale": false,
        "notDefaultCurrency": false,
        "exchangeRate": 1.0,
        "i18n": false,
        "privacyLog": "127.0.0.1\t\tnull\t"
    },
    "LOAD_LEVEL_GENERAL": "10",
    "LOAD_LEVEL_WARNING": "20",
    "LOAD_LEVEL_LIMIT": "30",
    "LOAD_LEVEL_EXCEPT_AD_GENERAL": "40",
    "LOAD_LEVEL_EXCEPT_AD_WARNING": "50",
    "LOAD_LEVEL_EXCEPT_AD_LIMIT": "60",
    "loadLevel": "10",
    "target": "es_global_brand",
    "query": null,
    "count": "40",
    "page": "1",
    "url": "qa-search.ssglocal.com",
    "rUrl": "http://rsearch.ssglocal.com:9200",
    "port": "7000",
    "mbrPrefix": null,
    "display": null,
    "viewType": null,
    "useYn": null,
    "ctgId": null,
    "ctgLv": null,
    "ctgLast": null,
    "parentCtgId": null,
    "themeYn": null,
    "ctgIds": null,
    "themeCtgIds": null,
    "ctgDispInfo": null,
    "brand": "3000016643",
    "brandId": null,
    "size": null,
    "color": null,
    "benefit": null,
    "cls": null,
    "shpp": null,
    "venId": null,
    "splVenId": null,
    "lrnkSplVenId": null,
    "sizeclip": null,
    "pickuSalestr": null,
    "bshopId": null,
    "minPrc": null,
    "maxPrc": null,
    "filterSiteNo": "6005",
    "filter": null,
    "include": null,
    "exclude": null,
    "sort": "best",
    "typoErr": null,
    "oriQueryYn": null,
    "oriQuery": null,
    "recomQuery": null,
    "highlight": null,
    "salestrNo": null,
    "aplTgtMediaCd": "10",
    "siteShppcstPlcyDivCd": null,
    "perdcSalestrNo": null,
    "webDvicDivCd": "10",
    "perdcRsvtShppPsblYn": null,
    "mbrClubId": null,
    "inflow": null,
    "bookFlag": null,
    "bestFlag": null,
    "siteNo": "6004",
    "replaceQuery": null,
    "frgShppPsblYn": null,
    "srchItemIds": null,
    "srchRecipeIds": null,
    "srchPnshopIds": null,
    "srchSpPriceItemIds": null,
    "guideItemIds": null,
    "srchRecomItemIds": null,
    "dispCtgId": "",
    "dispCtgSubIds": null,
    "srchSeq": null,
    "pnshopYn": null,
    "aplRngTgtCd": null,
    "mobileApiYn": "N",
    "spType": null,
    "shpgMgzTypeCd": null,
    "rplcCacheKey": null,
    "shrtcCacheKey": null,
    "srchKwdCacheKey": null,
    "mbrKwdCacheKey": null,
    "obanjangCacheKey": null,
    "newsCacheKey": null,
    "spPriceCacheKey": null,
    "itemCacheKey": null,
    "optnCacheKey": null,
    "brandCacheKey": null,
    "bshopCacheKey": null,
    "srchPopKwdCacheKey": null,
    "clsFilter": null,
    "curaId": null,
    "prefixFilter": null,
    "srchInspStatCd": null,
    "srchStrtRegDts": null,
    "srchEndRegDts": null,
    "srchVer": 1.0,
    "apiVer": null,
    "srchFailYn": null,
    "jpage": null,
    "jcount": null,
    "srchModId": null,
    "vodYn": null,
    "itemCacheExpireTime": "300",
    "itemImgSize": null,
    "categoryCollectionName": "item",
    "srchOptnTypeCd": null,
    "bindKeys": ["KEY_ITEM"],
    "outofstockDisplayYn": true,
    "mobileAppType": null,
    "adYn": "N",
    "tagYn": "N",
    "itemDeduplicationYn": "N",
    "adSearchItemCount": 2,
    "grpAddrId": null,
    "shppcstId": null,
    "itemSiteNo": null,
    "tasteItemIds": null,
    "taste": null,
    "recommendYn": null,
    "stdCtgIds": null,
    "offlineStrId": null,
    "offlineBldgId": null,
    "offlineFloId": null,
    "sfStrLclsCtgId": null,
    "sfStrMclsCtgId": null,
    "foodGroupYn": null,
    "testRequest": null,
    "itemIds": null,
    "esurl": "http://qa-esearch.ssglocal.com:9200",
    "adSearch": false,
    "banrEverSearch": false,
    "pageToInt": 1,
    "emptyParam": false
}
                        """)
        )
                .andDo(MockMvcResultHandlers.print())
                .andDo(document("index",
                        relaxedRequestFields(
                                fieldWithPath("target").description("검색 target")
                        )
                )
                )
                .andDo(document("index",
                        relaxedResponseFields(
                                fieldWithPath("code").description("응답 코드"),
                                fieldWithPath("detailCode").description("상세 응답 코드")
                        )
                )
                )

    }
}